version: '2'
services:
  
  bootstrap:
    build: 
      context: ./
      dockerfile: ./monitored-geth-client/Dockerfile
    restart: always
    links:
      - netstats
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --identity "ethereum-testnet" --fast --rpc --rpcaddr "0.0.0.0" --rpcapi "admin,db,eth,debug,miner,net,shh,txpool,personal,web3" --ws --wsaddr "0.0.0.0" --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --nodiscover --verbosity 3 --rpccorsdomain="*" --networkid=1618 --unlock "0"  --password "/root/files/password"'

    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  
  ethminer:
    build: 
      context: ./
      dockerfile: ./monitored-geth-client/Dockerfile
    restart: always
    links:
      - bootstrap
      - netstats
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=1618 --rpc --fast --rpcaddr="0.0.0.0" --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303" --mine --minerthreads=1'
  
  netstats:
    build: 
      context: ./
      dockerfile: ./eth-netstats/Dockerfile
    restart: always
    environment:
      - WS_SECRET=eth-net-stats-secret
    ports:
      - "3000:3000"
  
  addons:
    build: addons
    ports:
      - "8080:80"